import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
export default function Home() {
  const [productsInfo, setProductsInfo] = useState([]);

  useEffect(() => {
    async function fetchProducts() {
      try {
        const response = await fetch("/api/products");

        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }

        const json = await response.json();
        setProductsInfo(json);
      } catch (error) {
        console.error("Error al obtener los productos:", error);
      }
    }
    fetchProducts();
  }, []);

  const categoriesName = productsInfo.map(p => p.category);
  console.log({categoriesName})
  return (
    <>
      <Head>
        <title>Active Wear-X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-5">
        <div>
          <h2 className="text-2xl">Smartphones</h2>
          <div className="py-4">
            <div className="w-64">
              <div className="bg-blue-100 p-5 rounded-xl">
                <Image
                  priority
                  src="/products/iphone.png"
                  alt="Celular iPhone"
                  width={500}
                  height={500}
                />
              </div>
              <div className="mt-2">
                <h3 className="font-bold text-lg">iPhone 14 Pro</h3>
              </div>
              <p className="text-sm mt-1 leading-4">
                Descubre el nuevo iPhone 14 Pro: pantalla OLED de 6.1 pulgadas,
                cámara triple de 12 MP con tecnología LiDAR, chip A18 Bionic,
                5G, y resistencia al agua y polvo IP68.
              </p>
              <div className="flex mt-1">
                <div className="text-2xl font-bold grow">$936</div>
                <button className="bg-emerald-400 text-white py-1 px-3 rounded-xl">
                  +
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
